# Generated by Django 5.1.6 on 2025-03-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_customer_managers_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=models.IntegerField(unique=True)),
        ),
    ]
