# Generated by Django 5.1.6 on 2025-03-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["product_number"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
