# Generated by Django 5.1.5 on 2025-05-09 12:40

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_productimage_is_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to=catalog.models.product_image_path),
        ),
    ]
