# Generated by Django 5.1.5 on 2025-05-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-available", "id"]},
        ),
    ]
