# Generated by Django 5.1.5 on 2025-05-21 16:23

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-available", "id"],
                "verbose_name": "товар",
                "verbose_name_plural": "товари",
            },
        ),
        migrations.AlterField(
            model_name="country",
            name="ua_name",
            field=models.CharField(max_length=60, unique=True, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Наявність"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("1", "Одяг"), ("2", "Взуття"), ("3", "Аксесуари")],
                max_length=2,
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.country",
                verbose_name="Країна",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_high",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(10000)],
                verbose_name="Ціна до",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_low",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(10000)],
                verbose_name="Ціна від",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_number",
            field=models.IntegerField(unique=True, verbose_name="Код товару"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=catalog.models.product_image_path, verbose_name="Зображення"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Основне"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.product",
                verbose_name="Товар",
            ),
        ),
    ]
