# Generated by Django 5.1.5 on 2025-06-12 18:02

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_product_options_alter_country_ua_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductWishlistStats",
            fields=[],
            options={
                "verbose_name": "Бажаний товар",
                "verbose_name_plural": "Товари зі списків бажань",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
        migrations.CreateModel(
            name="WishlistThroughProxy",
            fields=[],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "список бажань",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.customer_wishlist",),
        ),
        migrations.AlterModelOptions(
            name="accessory",
            options={"verbose_name": "аксесуар", "verbose_name_plural": "аксесуари"},
        ),
        migrations.AlterModelOptions(
            name="clothing",
            options={"verbose_name": "одяг", "verbose_name_plural": "одяг"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["ua_name"],
                "verbose_name": "країна",
                "verbose_name_plural": "країни",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "клієнт", "verbose_name_plural": "клієнти"},
        ),
        migrations.AlterModelOptions(
            name="footwear",
            options={"verbose_name": "взуття", "verbose_name_plural": "взуття"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={"verbose_name": "зображення", "verbose_name_plural": "зображення"},
        ),
        migrations.AlterField(
            model_name="country",
            name="en_name",
            field=models.CharField(
                max_length=60, unique=True, verbose_name="назва англійською"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="ua_name",
            field=models.CharField(max_length=60, unique=True, verbose_name="країна"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="в наявності"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("1", "Одяг"), ("2", "Взуття"), ("3", "Аксесуари")],
                max_length=2,
                verbose_name="категорія",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.country",
                verbose_name="країна",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="опис"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="назва"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_high",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name="ціна до",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_low",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name="ціна від",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_number",
            field=models.IntegerField(
                editable=False, unique=True, verbose_name="код товару"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=catalog.models.product_image_path, verbose_name="зображення"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="основне зображення"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.product",
                verbose_name="товар",
            ),
        ),
    ]
