# Generated by Django 5.1.5 on 2025-07-03 13:14

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_productwishliststats_wishlistthroughproxy_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-available", "-id"],
                "verbose_name": "товар",
                "verbose_name_plural": "товари",
            },
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                unique=True,
                upload_to=catalog.models.product_image_path,
                verbose_name="зображення",
            ),
        ),
    ]
